In [23]:
#Question 1
import numpy as np

random_array = np.random.randint(1, 101, size = 10)
print(random_array)
print("First element:", random_array[0])
print("Last element:", random_array[-1])
random_array_floats = np.random.rand(3, 3)
print(random_array_floats)

[46 34 63 51 52 60  4 96  7 67]
First element: 46
Last element: 67
[[0.54131273 0.3299058  0.06850662]
 [0.19162278 0.85073865 0.61384856]
 [0.58282563 0.7014863  0.79749613]]


In [26]:
#Question 2
print("First row:", random_array_floats[0])
print("Last column:", random_array_floats[:, -1])

sub_array = random_array_floats[:2, :2]
print("Subarray consisting of the first two rows and first two columns:")
print(sub_array)

First row: [0.54131273 0.3299058  0.06850662]
Last column: [0.06850662 0.61384856 0.79749613]
Subarray consisting of the first two rows and first two columns:
[[0.54131273 0.3299058 ]
 [0.19162278 0.85073865]]


In [16]:
#Question 3 
random_array0 = np.random.randint(1, 101, size = 5)
random_array1 = np.random.randint(1, 101, size = 5)
print("Random array 1:", random_array0)
print("Random array 2:", random_array1)
add_result_array = random_array0 + random_array1
print("Adding the arrays:", add_result_array)
multiply_result_array = random_array0 * random_array1
print("Multiplying the arrays (element wise):", multiply_result_array)
square_result_array = random_array0 ** 2
print("Square of every element in the first array:", square_result_array)

Random array 1: [70  1 42  1 43]
Random array 2: [36 58 39 80  5]
Adding the arrays: [106  59  81  81  48]
Multiplying the arrays (element wise): [2520   58 1638   80  215]
Square of every element in the first array: [4900    1 1764    1 1849]


In [20]:
#Question 4
A = np.random.randint(1, 101, size = (2, 3))
B = np.random.randint(1, 101, size = (3, 2))
result = np.dot(A, B)
print("Result of matrix multiplication between A and B:")
print(result)
#No you cannot perform element-wise multiplication using the * operator because the array shapes are different.

Result of matrix multiplication between A and B:
[[11653  5888]
 [ 8672  7176]]
